### get all users
GET http://localhost:8080/

### get user by id
GET http://localhost:8080/users/1

### create user
POST http://localhost:8080/users

{
    "name": "John Doe",
    "email": "a@a.com"
}

### update user
PUT http://localhost:8080/users/1

{
    "name": "Rafael Sousa",
    "email": "a@a.com"
}

### delete user
DELETE http://localhost:8080/users/1